### ISSUE TITLE
`file_url` and `large_file_url` always 403 when on danbooru.donmai.us

### ISSUE THREAD

**Issue by valyrie97** [stawberri/danbooru-node#10]
Images loaded from `raikou1`, `raikou2`, etc. always load properly, however, when a link is from `danbooru.donmai.us`, it fails with a 403. 

Going to the image links manually work fine, but never in the page, with an `img` tag or `background: url()`. This may well be out of scope for this project, as im realizing this is a common issue with others who implement the API, like the hover zoom extension _Imagus_.

_Edit: the `?idk=0.93458673945` is for cache busting, while i was tesing the error, and has no effect on the results. images that 403 are consistent in their behaviour_

![image](https://user-images.githubusercontent.com/6365746/68454394-749fbf00-01c6-11ea-9f6a-4372c086742a.png)

**Comment by stawberri** [comment]
I think that this issue may be a relatively recent development compared to this module. Errors like this popped up occasionally when I was working on it, but never to the point where it was consistent. My guess would be that Danbooru may have implemented stricter hotlink prevention recently that's causing this!

I can't figure out how raikou works at all so I can't really provide any suggestions on that. 😥

**Comment by valyrie97** [comment]
Entirely fair, right around the time when I last used the api, according to git, 7 months ago, it was an issue, but much less so.

I took the liberty of running fiddler against the [cross site request that failed and the hotlinked version](https://gist.github.com/marcus13345/916e0f4e3b9461f3c17fd6b3647f1582). It looks like those headers are the root cause. Do you know of any proxies out there to act as a workaround? I've tried to use [crossorigin.me](https://corsproxy.github.io/), but I've either crashed it, or it was down to begin with.

**Comment by stawberri** [comment]
I don’t, but maybe you can make your own with something like [Glitch](https://glitch.com/)? That’s not really what it’s meant for and they might object if you’re making something that might see heavy traffic, though.

**Comment by valyrie97** [comment]
Alrighty then, I'll close this for now, reopen it if I have any more useful information. Or feel free to reopen it for tracking. Thanks!
