### ISSUE TITLE
booru.posts sending response data instead of the post.

### ISSUE THREAD

**Issue by Kikasuru** [stawberri/danbooru-node#16]
Heyo, not sure if this project is still active or if it's getting any updates, but I have encountered a bug.

When I call the `booru.posts` function, I don't get the post object, instead, I get completely useless data.

Data shown below.
`[ [Symbol(status)]: 200,
  [Symbol(data)]: '[]',
  [Symbol(headers)]: { date: 'Thu, 23 Jan 2020 01:55:32 GMT',
    'content-type': 'application/json; charset=utf-8',
    'content-length': '2',
    connection: 'close',
    'set-cookie':
     [ '__cfduid=dcd8391fbadbe10a1d960aec15fe8a1b51579744532; expires=Sat, 22-Feb-20 01:55:32 GMT; path=/; domain=.donma
i.us; HttpOnly; SameSite=Lax',
       '_danbooru2_session=xc%2FkzAs9W%2F9ht19L8ezVKPK%2B9hZbx8Dn5B4rSFKk%2FBAg0eSFmFrVyX2%2BUUu%2BqFOVQywwobed9vJK4oQh%
2BKWAYVOZWiExJ4iw%2BVHUBWgXW69psoWvMxTSQVe6C867HYZrpFLfKW3cDLHJOywcl7Uyfuh0Iq4WcNO8zefeIy6jBcnHiNVhBn%2FVtsK80VLHF1X1dkM
xqJ%2Ba0l5TCWbYezmYKIEdRW76CUHyCnxVDMrj%2FpNPqA2eNwfeo38XXYB8Wx14fq03hZF33rShpftIvtTDEqd1H40%3D--S2XUWEdcw151HU4A--Xi4h2
8XC82R2unrT4zokSg%3D%3D; domain=.donmai.us; path=/; expires=Mon, 23 Jan 2040 01:55:32 GMT; secure; HttpOnly; SameSite=La
x' ],
    'x-frame-options': 'SAMEORIGIN',
    'x-xss-protection': '1; mode=block',
    'x-content-type-options': 'nosniff',
    'x-download-options': 'noopen',
    'x-permitted-cross-domain-policies': 'none',
    'referrer-policy': 'strict-origin-when-cross-origin',
    'access-control-allow-origin': '*',
    etag: 'W/"4f53cda18c2baa0c0354bb5f9a3ecbe5"',
    'cache-control': 'max-age=0, private, must-revalidate',
    'x-request-id': '9cf09e8d-c048-4125-8824-51807a2ce647',
    'x-runtime': '0.069600',
    'cf-cache-status': 'DYNAMIC',
    'expect-ct':
     'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
    'alt-svc': 'h3-24=":443"; ma=86400, h3-23=":443"; ma=86400',
    server: 'cloudflare',
    'cf-ray': '5596255f1deb9b12-DFW' } ]`

**Comment by jyling** [comment]
Hi, I also received the same thing, since you already closed the issue, is the problem solved ?, if so what are your solution?
