### ISSUE TITLE
Get image URL

### ISSUE THREAD

**Issue by ghost** [stawberri/danbooru-node#5]
Hi,

Can you search for an image using the npm package then return the image's URL instead of downloading it? If so, how?

Thanks

**Comment by stawberri** [comment]
I think I had been planning to make an easy way to do this via a property, but never got around to doing it.

You can access Danbooru's response data directly via `post.raw`, though, so paths are available from:

Size | Thumbnail | Regular | Full size
-|-|-|-
Property | `post.raw.preview_file_url` | `post.raw.file_url` | `post.raw.large_file_url`

These look like paths starting with `/`, so just concatenate one to Danbooru's hostname and it should work.

**Comment by ghost** [comment]
Thank you, I'll look into it!
