### ISSUE TITLE
posts array sometimes false?

### ISSUE THREAD

**Issue by tzlils** [stawberri/danbooru-node#7]
I have this code
```			booru.posts({ tags: 'rating:e order:favcount limit:200' }).then(posts => {
				console.log(posts instanceof Array);
				const newPosts = posts.filter(item => item !== undefined);
				const index = Math.floor(Math.random() * newPosts.length);
				const post = newPosts[index]; 
				const url = booru.url(post.file_url)
  				const name = `${post.md5}.${post.file_ext}`
				if (post.file_ext == ".mp4") {
					msg.edit(url);
					return;
				}
```
And it works most of the time but sometimes `console.log(posts instanceof Array);` returns false instead of true, And then i get an undefined response! Please help me

**Comment by stawberri** [comment]
Hmm, this isn't really enough information for me to know what's happening. Instead of `console.log(posts instanceof Array);`, could you try something like this?

```js
if (posts instanceof Array) {
  console.log('posts is an array')
} else {
  console.log(JSON.stringify(posts))
}
```

This would allow us to see what `posts` actually looks like when it's not an array.

**Comment by tzlils** [comment]
It actually seems to work better now, i dont know why, but the time it didnt work i got
```cmd
2018-07-16T14:46:56.125927+00:00 app[worker.1]: false
2018-07-16T14:46:56.125997+00:00 app[worker.1]: {"success":false,"message":"The database timed out running your query."}
2018-07-16T14:46:56.126444+00:00 app[worker.1]: (node:20) UnhandledPromiseRejectionWarning: TypeError: posts.filter is not a function
```
I see the problem though, it becomes not an array and then i cant filter it, i tried to do `console.log(typeof posts);` and i found out that the array turns into an object for some reason, when it dosent work it returns object but when it does it returns an array, im very lost, i dont understand why this is happening

**Comment by stawberri** [comment]
It looks like the database timed out while running your query.

What kind of searches are you doing? Is this something where you're doing the same search every time, and it only works some of the time, or are there specific searches that cause this problem?

If it's the former (same search every time), I would put in a check to see if it's an object with `success` set to `false` and then retry.

```js
if ('success' in posts && !posts.success) {
  setTimeout(() => {
    console.log(`Error: ${posts.message}\nRetrying in 1 second...`)
    // Recursively call your function that fetches posts here.
  }, 1000)
} else {
  // The rest of your code goes here.
}
```

If it's the latter and it's certain requests that are causing issues, I would just show an error message to the user. You can just display `posts.message` and it'll probably be friendly enough.

**Comment by Terradice** [comment]
### nigge

**Comment by tzlils** [comment]
It worked! now it will repeat until it gets a proper result! thank you!
