### ISSUE TITLE
authenticated post queries return 404s in the browser

### ISSUE THREAD

**Issue by valyrie97** [stawberri/danbooru-node#8]
```
OPTIONS https://danbooru.donmai.us/posts.json?tags=rating%3Asafe&limit=200 404
[ stack ]
index.html#:1 Access to fetch at 'https://danbooru.donmai.us/posts.json?tags=rating%3Asafe&limit=200' from origin 'http://localhost' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
index.html#:1 Uncaught (in promise) TypeError: Failed to fetch
```

im not sure if this behaviour is intentional, or a bug. the same code works on the serverside, authenticated or not. however, on the browser, only unauthenticated works. If this isnt intended behaviour, this also might not be a problem with the library, but rather danbooru itself not allowing other domains via CORS.

**Comment by stawberri** [comment]
Ooh, this might be because of the authentication header. I'll have to look into this sometime this week to see if I can switch authentication over to using query string parameters instead.

**Comment by stawberri** [comment]
I still need to test it, but I think this might work! If you would like to test it yourself, you can install it with:

`npm install danbooru@3.1.0-0`

**Comment by stawberri** [comment]
This new version works, as long as you're doing `GET` requests (posts listing and everything else that fetches data is a `GET` request).

Trying to modify things may fail in browsers, due to Danbooru's security settings.

**Comment by valyrie97** [comment]
works great, thanks!
